version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "80:80"
    volumes:
      - /Users/pelinaybar/PycharmProjects/ToDoAppGemini/sql_app.db:/app/sql_app.db

